# Linear Algebra Using Python

**Course:** CSCN8000 — Artificial Intelligence Algorithms and Mathematics
**Lab:** 1 — Basic NumPy Operations
**Name:** Nnamdi Ikengah
**Student ID:** 9085175

---

## 1. Objectives

This notebook demonstrates the core array and linear-algebra operations provided by NumPy. By the end of it, the following should be clear:

- How to generate arrays with a controlled step, and with random values.
- How to index and slice two-dimensional arrays to extract specific rows.
- How to combine arrays by stacking, and how to split them apart again along a chosen axis.
- How matrix multiplication depends on dimension compatibility, and why some products are undefined.
- How reshaping changes an array's shape and dimensionality without changing its data.
- How broadcasting applies an operation across arrays of different shapes.
- How the rank of a coefficient matrix and of its augmented matrix together determine whether a system of linear equations has no solution, exactly one, or infinitely many.

The work is divided into **Part A** (Sections 3–5, array and matrix operations) and **Part B** (Section 6, solving systems of linear equations).

## 2. Required Libraries

The notebook depends on a single external library, **NumPy**, which supplies the `ndarray` type used throughout and the linear-algebra routines in `numpy.linalg`.

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.5.3


## 3. Array Creation and Indexing

### 3.1 Generating an Evenly Spaced Array

**Concept.** `np.arange(start, stop, step)` builds a one-dimensional array by starting at `start` and repeatedly adding `step`, stopping *before* `stop` is reached. The interval is half-open: `start` is included, `stop` is not.

**Task 2.** Create an array that starts at 1 and ends at 20, incremented by 3.

In [2]:
# --- Task 2 ---
# Build a sequence from 1 up to (but not including) 20, in steps of 3
array_2 = np.arange(1, 20, 3)

print("array_2 =", array_2)
print("Number of elements:", array_2.size)

array_2 = [ 1  4  7 10 13 16 19]
Number of elements: 7


**Interpretation.** The result is `[1, 4, 7, 10, 13, 16, 19]` — seven elements. The sequence stops at 19 rather than reaching 20, because the next value would be 22, which exceeds the exclusive upper bound. This half-open convention is the same one Python's built-in `range` follows, and it is the reason the endpoint does not appear in the output. When the endpoint *must* be included, `np.linspace` is the appropriate function instead, since it takes a count rather than a step.

### 3.2 Generating a Random Array

**Concept.** `np.random.rand(n)` returns `n` samples drawn from a continuous uniform distribution over the half-open interval [0, 1). Every value in that interval is equally likely; 0 is attainable, 1 is not.

**Task 3.** Create a new array of shape 3 containing random numbers between 0 and 1.

In [3]:
# --- Task 3 ---
# Draw 3 samples from a uniform distribution over [0, 1)
array_3 = np.random.rand(3)

print("array_3 =", array_3)
print("Minimum drawn:", array_3.min(), "| Maximum drawn:", array_3.max())

array_3 = [0.7366652  0.73863041 0.45977171]
Minimum drawn: 0.4597717057085504 | Maximum drawn: 0.7386304052763639


**Interpretation.** All three values fall inside [0, 1), as the uniform distribution guarantees. Because the underlying generator is seeded from system entropy by default, re-running this cell produces a different array every time. For results that need to be reproducible — sharing output, or debugging — the generator can be fixed with `np.random.seed(...)`, which causes the same sequence to repeat on every run. The values are not truly random but *pseudo*-random: a deterministic algorithm produces a sequence that is statistically indistinguishable from a uniform sample.

### 3.3 Slicing a Two-Dimensional Array

**Concept.** A 2D array is indexed as `array[rows, columns]`. A slice `a:b` selects indices from `a` up to but not including `b`. A negative start counts backwards from the end, so `-2:` means "the last two". A bare `:` in the column position keeps every column.

**Task 4.** Slice a 3×3 array to obtain the first two rows and the last two rows.

In [4]:
# --- Task 4 ---
array_4 = np.array([[10, 20, 45],
                    [30, 12, 16],
                    [42, 17, 56]])

# First two rows: indices 0 and 1, all columns
forward_slice = array_4[:2, :]

# Last two rows: counting backwards from the end, all columns
backward_slice = array_4[-2:, :]

print("Original array (shape {}):".format(array_4.shape))
print(array_4)
print("\nFirst two rows  ->", forward_slice.shape)
print(forward_slice)
print("\nLast two rows   ->", backward_slice.shape)
print(backward_slice)

Original array (shape (3, 3)):
[[10 20 45]
 [30 12 16]
 [42 17 56]]

First two rows  -> (2, 3)
[[10 20 45]
 [30 12 16]]

Last two rows   -> (2, 3)
[[30 12 16]
 [42 17 56]]


**Interpretation.** `array_4[:2, :]` returns rows 0 and 1, while `array_4[-2:, :]` returns rows 1 and 2. The middle row `[30, 12, 16]` appears in **both** results — in a three-row array the first two and the last two rows necessarily overlap. Worth noting too that basic slicing returns a *view* onto the original array rather than a copy: modifying `forward_slice` in place would also modify `array_4`. An explicit `.copy()` is required when independent data is needed.

## 4. Combining and Splitting Arrays

### 4.1 Stacking and Splitting

**Concept.** `np.vstack` joins arrays along the vertical axis (axis 0), placing them one on top of another and increasing the row count. `np.hstack` joins along the horizontal axis (axis 1), placing them side by side and increasing the column count. `np.split(array, n)` divides an array into `n` equal parts — but it splits along **axis 0 by default**, regardless of which axis was originally used to join.

**Task 5.** Stack two 2×2 arrays vertically and horizontally, then split the result back apart.

In [5]:
# --- Task 5 ---
arr_A = np.array([[1, 2], [3, 4]])
arr_B = np.array([[5, 6], [7, 8]])

# Stack vertically -> rows are appended, producing a 4x2 array
vert_stack = np.vstack([arr_A, arr_B])

# Stack horizontally -> columns are appended, producing a 2x4 array
horizontal_stack = np.hstack([arr_A, arr_B])

print("Vertical stack", vert_stack.shape)
print(vert_stack)
print("\nHorizontal stack", horizontal_stack.shape)
print(horizontal_stack)

# Split using the default axis (0) -- divides the 2x4 array by rows
split_default = np.split(horizontal_stack, 2)
print("\nSplit along default axis=0 (by rows):")
for part in split_default:
    print(part, "-> shape", part.shape)

# Split along axis 1 -- divides by columns, undoing the horizontal stack
split_axis1 = np.split(horizontal_stack, 2, axis=1)
print("\nSplit along axis=1 (by columns):")
for part in split_axis1:
    print(part, "-> shape", part.shape)

Vertical stack (4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stack (2, 4)
[[1 2 5 6]
 [3 4 7 8]]

Split along default axis=0 (by rows):
[[1 2 5 6]] -> shape (1, 4)
[[3 4 7 8]] -> shape (1, 4)

Split along axis=1 (by columns):
[[1 2]
 [3 4]] -> shape (2, 2)
[[5 6]
 [7 8]] -> shape (2, 2)


**Interpretation.** Stacking the same two 2×2 arrays gives different shapes depending on the axis used: `vstack` produces a 4×2 array, `hstack` a 2×4 array. The two splits then show why the `axis` argument matters. Splitting the horizontal stack along the **default axis 0** cuts it by rows into two 1×4 arrays, which does *not* recover the original inputs. Splitting along **axis 1** cuts by columns and returns exactly `arr_A` and `arr_B`.

The general rule: to reverse a join, split along the same axis that was used to combine. Because `np.split` defaults to axis 0 while `hstack` operates on axis 1, the default is the wrong choice for undoing a horizontal stack.

## 5. Matrix Operations

### 5.1 Matrix Multiplication and Dimension Compatibility

**Concept.** For the matrix product `A · B` to be defined, the number of **columns** of `A` must equal the number of **rows** of `B`. If `A` is (m × n) and `B` is (n × p), the product is (m × p): the inner dimensions cancel and the outer dimensions survive. Matrix multiplication is therefore not commutative — `A · B` may be well-defined while `B · A` is undefined.

**Task 6.** Multiply a 3×3 matrix by a 3×2 matrix, and demonstrate a case where multiplication is not possible.

In [6]:
# --- Task 6 ---
X = np.array([[5, 7, 2],
              [4, 5, 6],
              [7, 4, 2]])

Y = np.array([[4, 2],
              [6, 2],
              [4, 2]])

print("X has shape", X.shape, "and Y has shape", Y.shape)

# Valid: inner dimensions are (3, 3) -> they match, result is 3x2
multiplied_mat = np.dot(X, Y)
print("\nX . Y is valid -> shape", multiplied_mat.shape)
print(multiplied_mat)

# Invalid: reversing the order pairs Y (3x2) with X (3x3).
# The inner dimensions are now 2 and 3, which do not match.
print("\nAttempting Y . X:")
try:
    np.dot(Y, X)
except ValueError as e:
    print(f"Multiplication Error: {e}")

X has shape (3, 3) and Y has shape (3, 2)

X . Y is valid -> shape (3, 2)
[[70 28]
 [70 30]
 [60 26]]

Attempting Y . X:
Multiplication Error: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)


**Interpretation.** `X` is 3×3 and `Y` is 3×2. The inner dimensions match (3 and 3), so `np.dot(X, Y)` is defined and produces a 3×2 result — the outer dimensions of the operands. Reversing the order attempts `Y · X`, pairing a 3×2 with a 3×3; the inner dimensions become 2 and 3, which do not agree, and NumPy raises a `ValueError`.

Catching that error with `try`/`except` rather than letting it halt execution means the constraint is demonstrated explicitly while the notebook still runs top to bottom — which matters for a document that has to be re-run cleanly before submission.

### 5.2 Shape, Dimensionality, and Reshaping

**Concept.** Every array carries a `.shape` (a tuple giving its size along each axis) and an `.ndim` (the number of axes). `reshape` rearranges the same underlying data into a new shape, and the total element count must be preserved. Reshaping a flat vector of length 3 into `(3, 1)` makes it a two-dimensional column vector: the values are unchanged, but the array now has two axes instead of one.

**Task 7.** Find the shape and dimensions of two vectors, reshape them into column vectors, and report the dimensions afterwards.

In [7]:
# --- Task 7 ---
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Shape and dimensionality before reshaping
x_shape, x_dims = x.shape, x.ndim
y_shape, y_dims = y.shape, y.ndim

print("Before reshaping")
print("  x =", x, "| shape:", x_shape, "| ndim:", x_dims)
print("  y =", y, "| shape:", y_shape, "| ndim:", y_dims)

# Reshape both vectors into 3x1 column vectors
x_reshaped = x.reshape(3, 1)
y_reshaped = y.reshape(3, 1)

# Dimensionality after reshaping
x_reshaped_dims = x_reshaped.ndim
y_reshaped_dims = y_reshaped.ndim

print("\nAfter reshaping to (3, 1)")
print("  x_reshaped | shape:", x_reshaped.shape, "| ndim:", x_reshaped_dims)
print(x_reshaped)
print("  y_reshaped | shape:", y_reshaped.shape, "| ndim:", y_reshaped_dims)
print(y_reshaped)

Before reshaping
  x = [ 2 -1 -8] | shape: (3,) | ndim: 1
  y = [ 3  1 -2] | shape: (3,) | ndim: 1

After reshaping to (3, 1)
  x_reshaped | shape: (3, 1) | ndim: 2
[[ 2]
 [-1]
 [-8]]
  y_reshaped | shape: (3, 1) | ndim: 2
[[ 3]
 [ 1]
 [-2]]


**Interpretation.** Both `x` and `y` begin as one-dimensional arrays of shape `(3,)` with `ndim = 1`. A shape of `(3,)` is a flat vector — it carries no notion of being a row or a column. After reshaping to `(3, 1)` the `ndim` rises to 2, and the arrays become genuine column vectors with three rows and one column.

The element count is identical before and after; reshaping only reinterprets how the existing data is addressed, which is why NumPy can usually do it without copying. The distinction matters in linear algebra, because operations such as the matrix product treat a `(3,)` vector and a `(3, 1)` column vector differently.

### 5.3 Broadcasting

**Concept.** Broadcasting is the rule that lets NumPy apply an operation across arrays of different shapes without explicit loops. Shapes are compared axis by axis from the right; an axis of size 1, or an axis missing altogether, is stretched to match the other operand. Here a 1D array of length 3 is compared against a 3×3 matrix: it is treated as a single row and reused across all three rows.

**Task 8.** Subtract and multiply a 3×3 matrix by a 1D array using broadcasting.

In [8]:
# --- Task 8 ---
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

vector_1d = np.array([10, 20, 30])

print("matrix_3x3", matrix_3x3.shape, "and vector_1d", vector_1d.shape)

# The vector is broadcast across every row of the matrix
broadcast_subtraction = matrix_3x3 - vector_1d
broadcast_multiplication = matrix_3x3 * vector_1d

print("\nBroadcast subtraction (matrix - vector):")
print(broadcast_subtraction)
print("\nBroadcast multiplication (matrix * vector, element-wise):")
print(broadcast_multiplication)

matrix_3x3 (3, 3) and vector_1d (3,)

Broadcast subtraction (matrix - vector):
[[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]

Broadcast multiplication (matrix * vector, element-wise):
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


**Interpretation.** The vector `[10, 20, 30]` is applied column-wise to every row of the matrix. In the subtraction, 10 is removed from each element of column 0, 20 from column 1 and 30 from column 2 — so the first row `[1, 2, 3]` becomes `[-9, -18, -27]`. The multiplication follows the same pattern element by element.

It is worth stressing that `matrix_3x3 * vector_1d` is **not** matrix multiplication. The `*` operator performs element-wise multiplication with broadcasting, whereas a true matrix product requires `np.dot` or the `@` operator and would produce a different result entirely.

## 6. Part B — Solving Systems of Linear Equations

### 6.1 Concept: Rank and the Existence of Solutions

Any system of linear equations can be written in matrix form as **A · x = b**, where `A` is the coefficient matrix, `x` the vector of unknowns and `b` the vector of constants. Whether the system has a solution — and how many — is decided entirely by comparing two ranks:

- **rank(A)** — the rank of the coefficient matrix, and
- **rank([A | b])** — the rank of the *augmented* matrix, formed by appending `b` to `A` as an extra column.

The Rouché–Capelli theorem gives three cases:

| Condition | Outcome |
| --- | --- |
| rank(A) &lt; rank([A \| b]) | **No solution** — the system is inconsistent |
| rank(A) = rank([A \| b]) = number of unknowns | **Exactly one** unique solution |
| rank(A) = rank([A \| b]) &lt; number of unknowns | **Infinitely many** solutions — underdetermined |

The rank counts the number of linearly independent equations. If appending `b` *raises* the rank, then `b` lies outside the space reachable by combinations of the columns of `A`, and no assignment of the unknowns can satisfy every equation simultaneously.

### 6.2 Python Implementation

The two systems to analyse are:

```
System 1:   2*x1 + 3*x2 - 4*x3 =  6
            1*x1 - 4*x2 + 0*x3 =  8

System 2:   3*y1 - 4*y2 + 5*y3 = 10
           -1*y1 + 2*y2 - 4*y3 =  8
```

`np.linalg.matrix_rank` computes each rank and `np.column_stack` builds the augmented matrix. `np.linalg.solve` is called *only* in the unique-solution branch, because it requires a square, non-singular coefficient matrix and would raise an error otherwise.

In [9]:
# --- Part B ---
# System 1: 2x1 + 3x2 - 4x3 = 6 | x1 - 4x2 + 0x3 = 8
A1 = np.array([[2,  3, -4],
               [1, -4,  0]])
B1 = np.array([6, 8])

# System 2: 3y1 - 4y2 + 5y3 = 10 | -y1 + 2y2 - 4y3 = 8
A2 = np.array([[ 3, -4,  5],
               [-1,  2, -4]])
B2 = np.array([10, 8])


def analyze_and_solve_system(A, B):
    """Classify a linear system by comparing coefficient and augmented ranks."""
    num_vars = A.shape[1]
    rank_A = np.linalg.matrix_rank(A)

    # Create the augmented matrix [A | B]
    augmented_matrix = np.column_stack((A, B))
    rank_augmented = np.linalg.matrix_rank(augmented_matrix)

    print(f"  shape: {A.shape} | unknowns: {num_vars} | "
          f"rank(A): {rank_A} | rank([A|B]): {rank_augmented}")

    if rank_A < rank_augmented:
        return "No solutions (System is inconsistent)"
    elif rank_A == rank_augmented:
        if rank_A == num_vars:
            # A unique solution exists, so it is safe to solve directly
            solution = np.linalg.solve(A, B)
            return f"1 unique solution: {solution}"
        else:
            return "Infinite solutions (System is underdetermined)"


print("System 1")
print("  ->", analyze_and_solve_system(A1, B1))
print("\nSystem 2")
print("  ->", analyze_and_solve_system(A2, B2))

System 1
  shape: (2, 3) | unknowns: 3 | rank(A): 2 | rank([A|B]): 2
  -> Infinite solutions (System is underdetermined)

System 2
  shape: (2, 3) | unknowns: 3 | rank(A): 2 | rank([A|B]): 2
  -> Infinite solutions (System is underdetermined)


### 6.3 Verification and Interpretation

**Interpretation.** Both systems are classified as having **infinitely many solutions**, and the reason is structural rather than accidental.

Each system consists of only **two equations in three unknowns**. The coefficient matrix is therefore 2×3, and its rank cannot exceed 2 — strictly fewer than the three unknowns. In both cases the two equations are linearly independent, so rank(A) = 2; appending the constants does not raise the rank, so rank([A | b]) = 2 as well. The ranks agree, which makes each system *consistent*, but 2 < 3 leaves one **free variable**: fixing any value for it determines the remaining two, and every such choice produces a valid solution. The solution set is a line in three-dimensional space rather than a single point.

This also explains why `np.linalg.solve` is never reached for these inputs. That function requires a square coefficient matrix and would fail on a 2×3 input. Performing the rank comparison *first* diverts both systems to the underdetermined branch before any attempt to solve is made — which is precisely the value of checking rank before calling a solver.

## 7. Conclusion

This notebook worked through the NumPy operations that underpin practical linear algebra, and the results demonstrated the following:

- **Array construction** with `np.arange` (deterministic and evenly spaced) and `np.random.rand` (uniform over [0, 1)), including the half-open interval convention that both follow.
- **Indexing and slicing** of 2D arrays, covering negative indices and the overlap that necessarily arises when the first two and last two rows of a three-row array are taken.
- **Stacking and splitting**, which showed that reversing a join requires splitting along the same axis used to combine — `np.split` defaults to axis 0 and so will not undo an `hstack` unless told otherwise.
- **Matrix multiplication**, where the inner dimensions must agree, making the operation order-dependent and in some orderings undefined.
- **Shapes and reshaping**, which alter how data is addressed without altering the data itself, converting flat vectors into explicit column vectors.
- **Broadcasting**, which applies an operation element-wise across mismatched shapes and is distinct from true matrix multiplication.
- **Rank-based analysis of linear systems**, applying the Rouché–Capelli theorem to classify a system before attempting to solve it.

The Part B result illustrates the central principle most clearly: with two equations and three unknowns, no amount of computation can yield a single unique answer. Both systems are consistent but underdetermined, and their solution sets are lines rather than points. Comparing ranks first is what makes that conclusion available — and what prevents an inappropriate call to a solver that assumes a square system.